[package]
name = "vtf"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bincode = { version = "2.0.1", features = ["derive", "serde"] }
texpresso = "2.0.1"
thiserror = { workspace = true }
wasm-bindgen = { workspace = true }
