[package]
name = "bsp"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bincode = "2.0.0-rc.3"
lzma-rs = "0.3.0"
serde = { version = "1.0.217", features = ["derive"] }
tsify = "0.4.5"
wasm-bindgen = { workspace = true }
