[package]
name = "bsp"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bincode = { workspace = true }
lzma-rs = "0.3.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_with = "3.15.0"
thiserror = { workspace = true }
tsify = "0.4.5"
wasm-bindgen = { workspace = true }
